const dotenv = require("dotenv");
const dotenvExpand = require("dotenv-expand");

const envArg = process.argv.find(arg => arg.startsWith('--env='));
const envName = envArg ? envArg.split('=')[1] : 'server1';
const envFile = `.env.${envName}`;

const myEnv = dotenv.config({ path: envFile });
dotenvExpand.expand(myEnv);

const { formatCompanyPayload } = require("../Utils/Companies/formatCompany");

const OVERALL_LOG = process.env.COMPANY_OVERALL_LOG;
const ERROR_LOG = process.env.COMPANY_ERROR_LOG;

const data = {
  "attributes": {
    "type": "Account",
    "url": "/services/data/v64.0/sobjects/Account/0011U00000n6mV5QAI"
  },
  "Id": "0011U00000n6mV5QAI",
  "IsDeleted": false,
  "MasterRecordId": null,
  "Name": "Amber AI",
  "Type": "Client/Prospect",
  "RecordTypeId": "0121U0000005H4XQAU",
  "ParentId": "001Jw000000Z3awIAC",
  "BillingStreet": "Wickhams Cay II, Road Town, Tortola",
  "BillingCity": "British Virgin Islands",
  "BillingState": null,
  "BillingPostalCode": "VG1110",
  "BillingCountry": "British Indian Ocean Territory",
  "BillingLatitude": null,
  "BillingLongitude": null,
  "BillingGeocodeAccuracy": null,
  "BillingAddress": {
    "city": "British Virgin Islands",
    "country": "British Indian Ocean Territory",
    "geocodeAccuracy": null,
    "latitude": null,
    "longitude": null,
    "postalCode": "VG1110",
    "state": null,
    "street": "Wickhams Cay II, Road Town, Tortola"
  },
  "ShippingStreet": null,
  "ShippingCity": null,
  "ShippingState": null,
  "ShippingPostalCode": null,
  "ShippingCountry": null,
  "ShippingLatitude": null,
  "ShippingLongitude": null,
  "ShippingGeocodeAccuracy": null,
  "ShippingAddress": null,
  "Phone": "(852) 664-1976",
  "Fax": null,
  "AccountNumber": null,
  "Website": "http://www.ambergroup.io",
  "PhotoUrl": "/services/images/photo/0011U00000n6mV5QAI",
  "Sic": null,
  "Industry": "OTC/Liquidity Provider",
  "AnnualRevenue": 1.0E8,
  "NumberOfEmployees": 1000,
  "Ownership": null,
  "TickerSymbol": null,
  "Description": null,
  "Rating": null,
  "Site": null,
  "CurrencyIsoCode": "USD",
  "OwnerId": "005Jw000016tCkaIAE",
  "CreatedDate": "2019-08-01T03:48:55.000+0000",
  "CreatedById": "0051U000000KeO2QAK",
  "LastModifiedDate": "2026-01-23T11:18:38.000+0000",
  "LastModifiedById": "005Ro00000IQDFNIA5",
  "SystemModstamp": "2026-01-23T11:18:38.000+0000",
  "LastActivityDate": "2023-05-30",
  "LastViewedDate": "2026-01-23T11:18:38.000+0000",
  "LastReferencedDate": "2026-01-23T11:18:38.000+0000",
  "SourceSystemIdentifier": null,
  "IsPartner": false,
  "IsCustomerPortal": false,
  "ChannelProgramName": null,
  "ChannelProgramLevelName": null,
  "Jigsaw": null,
  "JigsawCompanyId": null,
  "AccountSource": "Website",
  "SicDesc": null,
  "OperatingHoursId": null,
  "ActivityMetricId": "0Gq1U000000VF2nSAG",
  "ActivityMetricRollupId": null,
  "IsPriorityRecord": false,
  "Latest_Closed_Date__c": "2020-10-01",
  "Business_Type__c": "Financial Services",
  "About__c": null,
  "Import2_Id__c": null,
  "Terms__c": "Net 30",
  "Client_Segment__c": "Institutional",
  "Account_Status__c": "Active",
  "Marketing_Participation_Last_Updated__c": null,
  "State_of_KYC__c": null,
  "Frozen_Termination_Date__c": null,
  "Unfunded_Account__c": false,
  "Termination_Date__c": null,
  "Number_of_Open_Opps__c": 1.0,
  "Number_of_Closed_Opps__c": 2.0,
  "Termination_Reason__c": null,
  "Past_Due_Invoice_Amount__c": null,
  "Owner_Email__c": "joantee@bitgo.com",
  "State__c": null,
  "Customer_Since_Date__c": "2019-09-04",
  "Domain__c": "ambergroup.io",
  "Client_Touch_Level__c": null,
  "engagio__Competitive_Intent_Keywords__c": null,
  "engagio__Competitive_Intent_Keywords_longtext__c": null,
  "engagio__CustomerDate__c": "2024-11-06T03:02:14.000+0000",
  "SFDC_18_ID__c": "0011U00000n6mV5QAI",
  "Region__c": "APAC",
  "RegionOverride__c": "APAC",
  "engagio__EngagedPeople__c": 0.0,
  "engagio__EngagementMinutesLast30Days__c": 9.0,
  "engagio__EngagementMinutesLast3Months__c": 37.0,
  "engagio__EngagementMinutesLast7Days__c": 2.0,
  "engagio__FirstEngagementDate__c": "2023-12-07T00:00:00.000+0000",
  "engagio__HighIntentKeywords__c": null,
  "engagio__HighIntentKeywords_longtext__c": null,
  "engagio__IntentMinutesLast30Days__c": null,
  "engagio__MQADate__c": null,
  "engagio__NumberOfPeople__c": 5.0,
  "engagio__PipelineDate__c": null,
  "engagio__Sales_Touches_14_days__c": null,
  "engagio__Sales_Touches_7_days__c": null,
  "engagio__Status__c": "Customer",
  "BitGo_Entity__c": "BitGo Trust Company Inc",
  "engagio__Top_Web_Traffic_URLs__c": "bitgo.com",
  "engagio__WebVisitsLast3Months__c": 36.0,
  "SYSTEM_DNU__c": null,
  "AccountTier__c": "Tier 2",
  "engagio__pipeline_predict_score__c": null,
  "engagio__qualification_score__c": null,
  "Organization_ID__c": null,
  "Enterprise_ID__c": null,
  "Enrichment__c": false,
  "TAG__c": "Team Clean Up",
  "Account_Owner_Full_Name__c": "Joan Tee",
  "Opportunity__c": null,
  "Owner_Team__c": null,
  "Parent_Account_Owner__c": "Joan Tee",
  "Reasons_for_no_CSM__c": null,
  "ParentId_18__c": "001Jw000000Z3awIAC",
  "Account_Annual_Revenue__c": null,
  "Notable_Brand__c": false,
  "Owner_By_Current_User__c": false,
  "Parent_Since_Date__c": null,
  "Conversion_Point__c": null,
  "Conversion_Point_Details__c": null,
  "rh2__Describe__c": null,
  "rh2__testCurrency__c": null,
  "Trade_Client__c": false,
  "Parent_Business_Type__c": null,
  "SalesLoft1__Active_Account__c": 0.0,
  "SalesLoft1__SalesLoft_Domain__c": "http://www.ambergroup.io?0011U00000n6mV5QAI",
  "CSM__c": "0051U000008qT2uQAE",
  "Market_Segment__c": "Trading Firms",
  "CSM_Call_Cadence__c": null,
  "New_Logo_Date__c": null,
  "Acct_Parent_Date__c": "2019-09-04",
  "Parent_Type__c": null,
  "DOZISF__ZoomInfo_Enrich_Status__c": null,
  "DOZISF__ZoomInfo_First_Updated__c": null,
  "DOZISF__ZoomInfo_Id__c": null,
  "If_so_for_which_Product__c": null,
  "Leverage_Wallet_Recovery_Wizard__c": false,
  "Logo_Usage__c": null,
  "Main_POC_Location__c": null,
  "DOZISF__ZoomInfo_InboxAI_ID__c": null,
  "DOZISF__ZoomInfo_Last_Updated__c": null,
  "DOZISF__ZoomInfo_Opsos_App_Field__c": null,
  "DOZISF__ZoomInfo_Opsos_Current_Endpoint__c": null,
  "DOZISF__ZoomInfo_Opsos_Last_Processed_Date__c": null,
  "Data_Breach_Notification_Required__c": false,
  "Paygo_After_Churn__c": false,
  "Data_Breach_Notification_Time__c": null,
  "Renewal_Date__c": null,
  "Sales_Name__c": "0051U000009fpKJQAY",
  "Special_Terms_and_Agreement__c": null,
  "Testnet_Activated__c": null,
  "Testnet_Engagement_Frequency__c": null,
  "Top_3_Account_Concerns__c": null,
  "Training__c": null,
  "Trust_Officer_Name__c": null,
  "Why_do_they_need_Testnet__c": null,
  "Mt_Gox_Org_Type__c": null,
  "Customer_Marketing__c": null,
  "CSM_Health_Score__c": null,
  "Application_Type__c": null,
  "Renewal_Date_Formula__c": "2020-08-31",
  "Renewal_Status_Validation__c": -1971.0,
  "Contract_Start_Date_Roll_Up__c": "2019-09-01",
  "Country_of_Primary_Business_Operations__c": "Hong Kong",
  "Market_Segment_Tier__c": "Tier 1",
  "Account_Owner_IsActive__c": true,
  "Sales__c": "0051U000009foiPQAQ",
  "Bank_Account__c": null,
  "SEN_Account__c": null,
  "Original_Account_Name__c": null,
  "Billing_Contact__c": "Tiantian Kullander",
  "Billing_Email__c": "trading@amberaigroup.com",
  "PD_Billing_Phone__c": "85255015058",
  "Client_Status__c": null,
  "KYC_Status__c": null,
  "BitGo_Entity_Internal_ID_MULESOFT__c": "3",
  "Additional_Email_1__c": null,
  "Additional_Email_2__c": null,
  "Additional_Email_3__c": null,
  "Additional_Email_4__c": null,
  "COMPANY_NAME_MULESOFT__c": null,
  "NetSuite_Id_New__c": "41889",
  "Sync_With_Netsuite__c": false,
  "Termination_Date_Time__c": null,
  "account_type__c": "entity",
  "Communication_Channels__c": null,
  "Coins_Client_Plans_to_Unlock__c": null,
  "Coins_on_Client_s_Platform__c": null
};

const payload = formatCompanyPayload(data, OVERALL_LOG, ERROR_LOG);

console.log({ payload });
